name: Build with packwiz

on:
    pull_request:
        branches: ["main", "Astral-Experimental"]
    push:
        branches: ["main", "Astral-Experimental"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Get latest packwiz binary
              id: download-packwiz
              uses: dawidd6/action-download-artifact@v2
              with:
                  workflow: go.yml
                  branch: main
                  name: Linux 64-bit x86
                  repo: packwiz/packwiz

            - name: Make packwiz binary executable
              run: chmod +x ./packwiz

            - name: Restore cached mod downloads
              id: cache-mods-restore
              uses: actions/cache/restore@v3
              with:
                  path: /home/runner/.cache/packwiz/cache
                  key: cached-mods
                  restore-keys: |
                      cached-mods-

            - name: Create CurseForge Zip
              run: |
                  ./packwiz curseforge export -o create_astral-gh_${{github.run_number}}.zip
              #   ./packwiz curseforge export -s server create_astral_server-gh_${{github.run_number}}.zip

            - name: Cache mod downloads
              id: cache-mods-save
              uses: actions/cache/save@v3
              with:
                  path: /home/runner/.cache/packwiz/cache
                  key: cached-packages-${{ hashFiles('/home/runner/.cache/packwiz/cache/**/*') }}

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  path: |
                      create_astral-gh_${{github.run_number}}.zip
                  #   create_astral_server-gh_${{github.run_number}}.zip
