name: Build with packwiz

on:
    pull_request:
        branches: ["main", "Astral-Experimental"]
    push:
        branches: ["main", "Astral-Experimental"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Get latest packwiz binary
              id: download-packwiz
              uses: dawidd6/action-download-artifact@v2
              with:
                  workflow: go.yml
                  branch: main
                  name: Linux 64-bit x86
                  repo: packwiz/packwiz

            - name: Make packwiz binary executable
              run: chmod +x ./packwiz

            - name: Create CurseForge Zip
              run: |
                  ./packwiz curseforge export

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: Create Astral (GH ${{github.run_id}})
                  path: ./*.zip
